# Generated by Django 3.1.7 on 2021-04-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitions',
            options={'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.AlterModelOptions(
            name='contests',
            options={'verbose_name': 'Contest', 'verbose_name_plural': 'Contests'},
        ),
        migrations.AlterModelOptions(
            name='solutions',
            options={'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
    ]
